# Generated by Django 5.0 on 2024-05-11 19:43

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_postal_code', models.CharField(max_length=8)),
                ('company_city', models.CharField(max_length=100)),
                ('company_country', models.CharField(max_length=100)),
                ('company_phone_number', models.CharField(max_length=20)),
                ('company_website', models.URLField()),
                ('leaderboard_enable', models.BooleanField(default=True)),
                ('leaderboard_default_anonymous', models.BooleanField(default=False)),
                ('leaderboard_groupby', models.IntegerField(default=1)),
                ('leaderboard_duration', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
