# Generated by Django 5.0 on 2024-05-14 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('settingsmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='schema_name',
        ),
        migrations.CreateModel(
            name='SettingsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='customers.client')),
            ],
        ),
    ]
