# Generated by Django 5.0 on 2024-05-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('settingsmanager', '0002_remove_settings_schema_name_settingscompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingscompany',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_company', to='customers.client'),
        ),
        migrations.CreateModel(
            name='SettingsLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('group_by', models.CharField(default='department', max_length=100)),
                ('privacy_default', models.BooleanField(default=True)),
                ('privacy_user_control', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_leaderboard', to='customers.client')),
            ],
        ),
    ]
