# Generated by Django 5.0 on 2024-05-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsmanager', '0003_alter_settingscompany_tenant_settingsleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingscompany',
            name='brand_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
