# Generated by Django 5.0 on 2024-06-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtraining', '0004_microtraining_default_active_and_more'),
        ('settingsmanager', '0004_settingscompany_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotrainingCategoryActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microtraining.microtrainingcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MicrotrainingTrainingActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microtraining.microtraining')),
            ],
        ),
    ]
