# Generated by Django 5.0 on 2024-06-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phishing', '0007_indicator_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MicroTrainingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('question_text', models.TextField()),
                ('answer1', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('answer3', models.CharField(max_length=255)),
                ('correct_answer_index', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.language')),
                ('microtraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='microtraining.microtraining')),
            ],
            options={
                'unique_together': {('microtraining', 'language')},
            },
        ),
    ]
