# Generated by Django 5.0 on 2024-06-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtraining', '0002_microtrainingcategory_microtraining_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtraining',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='microtrainings', to='microtraining.microtrainingcategory'),
            preserve_default=False,
        ),
    ]
