# Generated by Django 5.0 on 2024-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtraining', '0003_microtraining_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtraining',
            name='default_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='microtrainingcategory',
            name='default_active',
            field=models.BooleanField(default=True),
        ),
    ]
