# Generated by Django 5.0 on 2024-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('languages', models.JSONField(default=list)),
                ('category', models.IntegerField(max_length=2)),
                ('difficulty_level', models.IntegerField(max_length=2)),
                ('sending_email_address', models.EmailField(max_length=254)),
                ('sending_email_name', models.CharField(max_length=255)),
                ('sending_subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
