# Generated by Django 5.0 on 2024-05-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0003_phishingsimulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingcampaign',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phishingcampaign',
            name='difficulty_level',
            field=models.IntegerField(),
        ),
    ]
