# Generated by Django 5.0 on 2024-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0004_alter_phishingcampaign_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_id', models.CharField(max_length=50)),
                ('gif_type', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
            ],
        ),
    ]
