# Generated by Django 5.0 on 2024-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0006_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
