# Generated by Django 5.0 on 2024-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0007_indicator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('sender', 'Sender'), ('subject', 'Subject'), ('content', 'Content'), ('link', 'Link')], max_length=50),
        ),
    ]
